import { Inter } from 'next/font/google'
import './globals.css'
import NavbarComponent from '@/component/NavbarComponent'
import Footer from '@/component/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Tawheed Portfolio',
  description: 'Generated by Tawheed',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='!scroll-smooth'>
      <body className={inter.className}>
        <NavbarComponent/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
